.github/workflows/ci.yaml:
  env:
    - DOCKER_IMAGE: adorsys/java
      TAG: 8-ubi
      DIR: ubi/8
      SQUASH: 'true'
      ALIASES: '8'
    - DOCKER_IMAGE: adorsys/java
      TAG: 11-ubi
      DIR: ubi/11
      SQUASH: 'true'
      ALIASES: '11'
